#
# Docker compose configuration to run php app (like laravel) with transversal capabilities
#

version: '3'

networks:
  backend-lane:

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "${HOST_NGINX_HTTP_PORT}:80"
    volumes:
      - ${BACK_APP_SOURCE_PATH_HOST}:/var/www/app
      - ${NGINX_SITES_PATH_HOST}:/etc/nginx/sites-available
    depends_on:
      - php-fpm
    networks:
      - backend-lane

  php-fpm:
    build:
      context: ./php-fmp
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ${BACK_APP_SOURCE_PATH_HOST}:/var/www/app
    networks:
      - backend-lane
