#
# Docker compose configuration to run php app (like laravel) with transversal capabilities
#

version: '3'

# Docker network to interconnect services
networks:
  backend-lane:

volumes:
  # Volume for mysql database storage
  mysql-db-data:
  # Volume for pgsql database storage
  pgsql-db-data:
  # Redis persistence storage
  redis-db-data:
  # Composer cache
  composer-cache:
  # Caddy config cache
  caddy-data:
  caddy-config:

services:
  # Base service, nginx webserver that expose the app
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "${HOST_NGINX_HTTP_PORT}:80"
    volumes:
      - ${BACK_APP_SOURCE_PATH_HOST}:/var/www/app:delegated
      - ${NGINX_SITES_PATH_HOST}:/etc/nginx/sites-available:delegated
    depends_on:
      - php-fpm
    networks:
      - backend-lane

  # Container that runs tht php interpreter with fastcgi
  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ${BACK_APP_SOURCE_PATH_HOST}:/var/www/app:delegated
    depends_on:
      - ${ACTIVE_DATABASE}
      - redis
    networks:
      - backend-lane

  # Service to run composer in a dedicated container
  composer:
    build:
      context: ./composer
    container_name: composer
    volumes:
      - composer-cache:/tmp
      - ${BACK_APP_SOURCE_PATH_HOST}:/var/www/app
    working_dir: /var/www/app
    user: composer-www-data
    networks:
      - backend-lane
    entrypoint: ['composer', '--ignore-platform-reqs']

  # Service to run php-cli commands
  php-cli:
    build:
      context: ./php-cli
    container_name: php-cli
    volumes:
      - ${BACK_APP_SOURCE_PATH_HOST}:/var/www/app
    depends_on:
      - ${ACTIVE_DATABASE}
    working_dir: /var/www/app
    user: www-php-cli
    networks:
      - backend-lane
    entrypoint: ['php', '/var/www/app/${FRAMEWORK_CLI}']

  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SERVICE_TAGS= dev
      - SERVICE_NAME= mysql
      - TZ=${APP_TIMEZONE}
    volumes:
      - mysql-db-data:/var/lib/mysql
    networks:
      - backend-lane

  # PostgreSQL database
  pgsql:
    image: postgres:13-alpine
    container_name: pgsql
    ports:
      - "${HOST_PGSQL_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - pgsql-db-data:/var/lib/postgresql/data
    networks:
      - backend-lane

  # Redis database
  redis:
    image: redis:6.0-alpine
    command: redis-server
    volumes:
      - redis-db-data:/data
    ports:
      - ${HOST_REDIS_PORT}:6379
    networks:
      - backend-lane

  # Queues worker
  # TODO - test this service
  queues-worker:
    build:
      context: ./php-cli
    container_name: queues-worker
    volumes:
      - ${BACK_APP_SOURCE_PATH_HOST}:/var/www/app
    depends_on:
      - ${ACTIVE_DATABASE}
      - redis
    working_dir: /var/www/app
    user: www-php-cli
    networks:
      - backend-lane
    entrypoint: ['php', '/var/www/app/${FRAMEWORK_CLI}']

  # Meilisearch service
  meilisearch:
    image: getmeili/meilisearch:v0.14.1
    container_name: meilisearch
    ports:
      - ${HOST_MEILISEARCH_PORT}:7700
    networks:
      - backend-lane

  # Mail hog
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - ${HOST_MAILHOG_SMTP_PORT}:1025
      - ${HOST_MAILHOG_PORT}:8025
    networks:
      - backend-lane

  # Caddy 2 server, an alternative to NGINX
  caddy:
    image: caddy/2.2.0-alpine
    container_name: caddy
    ports:
      - "${HOST_CADDY_HTTP_PORT}:80"
      - "${HOST_CADDY_HTTPS_PORT}:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${BACK_APP_SOURCE_PATH_HOST}:/var/www/app
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - php-fpm
    networks:
      - backend-lane
